apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: pranjaldeka/flask-mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: "flask_db"
            - name: MONGO_AUTH_SOURCE
              value: "admin"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-root-credentials
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-root-credentials
                  key: mongo-root-password
          resources:
            requests:
              cpu: "0.2"
              memory: "250Mi"
            limits:
              cpu: "0.5"
              memory: "500Mi"
